// GENERATED by tools/gen_relay_vectors.mjs from cumulo-nimbus protocol.ts.
// Do NOT hand-edit. Regenerate on any protocol.ts change. PROTOCOL_VERSION=2.
#pragma once

struct RelayVec {
  const char* name;
  const char* json;
  int type;  // 1=welcome 2=req 3=pong 4=bye 5=ubegin 6=uchunk 7=uend 8=uabort
  unsigned heartbeatMs;
  const char* id;
  const char* method;
  const char* path;
  const char* bodyB64;
  const char* byeReason;  // bye + uabort reason
  const char* hdrKey;
  const char* hdrVal;
  unsigned totalLen;  // ubegin
  unsigned seq;       // uchunk
  unsigned off;       // uchunk
};

static const RelayVec kRelayVectors[] = {
  {"welcome", "{\"t\":\"welcome\",\"v\":2,\"heartbeatMs\":30000}", 1, 30000, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 0, 0, 0},
  {"req_get_no_body", "{\"t\":\"req\",\"id\":\"r1\",\"method\":\"GET\",\"path\":\"/api/state?t=abc\",\"headers\":{\"user-agent\":\"Mozilla/5.0\",\"accept\":\"application/json\"}}", 2, 0, "r1", "GET", "/api/state?t=abc", nullptr, nullptr, "user-agent", "Mozilla/5.0", 0, 0, 0},
  {"req_post_body", "{\"t\":\"req\",\"id\":\"r2\",\"method\":\"POST\",\"path\":\"/api/config\",\"headers\":{\"content-type\":\"application/json\"},\"bodyB64\":\"eyJkZXZOYW1lIjoiTmltYnVzIn0=\"}", 2, 0, "r2", "POST", "/api/config", "eyJkZXZOYW1lIjoiTmltYnVzIn0=", nullptr, "content-type", "application/json", 0, 0, 0},
  {"pong", "{\"t\":\"pong\",\"ts\":1786900000000}", 3, 0, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 0, 0, 0},
  {"bye_unpaired", "{\"t\":\"bye\",\"reason\":\"unpaired\"}", 4, 0, nullptr, nullptr, nullptr, nullptr, "unpaired", nullptr, nullptr, 0, 0, 0},
  {"bye_revoked", "{\"t\":\"bye\",\"reason\":\"revoked\"}", 4, 0, nullptr, nullptr, nullptr, nullptr, "revoked", nullptr, nullptr, 0, 0, 0},
  {"ubegin", "{\"t\":\"ubegin\",\"id\":\"u1\",\"method\":\"POST\",\"path\":\"/api/music/upload?name=song.mp3\",\"headers\":{\"content-type\":\"multipart/form-data; boundary=X\"},\"totalLen\":5000000}", 5, 0, "u1", "POST", "/api/music/upload?name=song.mp3", nullptr, nullptr, "content-type", "multipart/form-data; boundary=X", 5000000, 0, 0},
  {"uchunk", "{\"t\":\"uchunk\",\"id\":\"u1\",\"seq\":0,\"off\":0,\"bodyB64\":\"aGVsbG8gY2h1bms=\"}", 6, 0, "u1", nullptr, nullptr, "aGVsbG8gY2h1bms=", nullptr, nullptr, nullptr, 0, 0, 0},
  {"uend", "{\"t\":\"uend\",\"id\":\"u1\"}", 7, 0, "u1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 0, 0, 0},
  {"uabort", "{\"t\":\"uabort\",\"id\":\"u1\",\"reason\":\"client_abort\"}", 8, 0, "u1", nullptr, nullptr, nullptr, "client_abort", nullptr, nullptr, 0, 0, 0},
};
static const int kRelayVectorCount = 10;
