// GENERATED by tools/gen_relay_vectors.mjs from cumulo-nimbus protocol.ts.
// Do NOT hand-edit. Regenerate on any protocol.ts change. PROTOCOL_VERSION=1.
#pragma once

struct RelayVec {
  const char* name;
  const char* json;
  int type;  // 1=welcome 2=req 3=pong 4=bye
  unsigned heartbeatMs;
  const char* id;
  const char* method;
  const char* path;
  const char* bodyB64;
  const char* byeReason;
  const char* hdrKey;
  const char* hdrVal;
};

static const RelayVec kRelayVectors[] = {
  {"welcome", "{\"t\":\"welcome\",\"v\":1,\"heartbeatMs\":30000}", 1, 30000, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
  {"req_get_no_body", "{\"t\":\"req\",\"id\":\"r1\",\"method\":\"GET\",\"path\":\"/api/state?t=abc\",\"headers\":{\"user-agent\":\"Mozilla/5.0\",\"accept\":\"application/json\"}}", 2, 0, "r1", "GET", "/api/state?t=abc", nullptr, nullptr, "user-agent", "Mozilla/5.0"},
  {"req_post_body", "{\"t\":\"req\",\"id\":\"r2\",\"method\":\"POST\",\"path\":\"/api/config\",\"headers\":{\"content-type\":\"application/json\"},\"bodyB64\":\"eyJkZXZOYW1lIjoiTmltYnVzIn0=\"}", 2, 0, "r2", "POST", "/api/config", "eyJkZXZOYW1lIjoiTmltYnVzIn0=", nullptr, "content-type", "application/json"},
  {"pong", "{\"t\":\"pong\",\"ts\":1786900000000}", 3, 0, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
  {"bye_unpaired", "{\"t\":\"bye\",\"reason\":\"unpaired\"}", 4, 0, nullptr, nullptr, nullptr, nullptr, "unpaired", nullptr, nullptr},
  {"bye_revoked", "{\"t\":\"bye\",\"reason\":\"revoked\"}", 4, 0, nullptr, nullptr, nullptr, nullptr, "revoked", nullptr, nullptr},
};
static const int kRelayVectorCount = 6;
