#!/usr/bin/env python3
"""sounds embed - basic-tier WAVs -> src/sfx/sfx_basic_data.h (flash rodata).

Parses each dist/basic/<slug>.wav (16-bit mono PCM) and emits one generated
header with the raw PCM samples + rate per clip. `const` arrays land in .rodata
(DROM flash) on the ESP32-S3 - no PROGMEM juggling; the device plays them with
solide::audio::playPcm() straight from flash, so the basic set needs NO
filesystem at all (works with zero SD + zero WiFi, forever).

Include the header from exactly ONE translation unit (src/sfx/sound_fx.cpp).
Re-runnable: regenerates the header wholesale. Run after build_assets.py.
Schema is byte-compatible with the earlier embed-basic generator output
(namespace sfx_basic, Clip{slug,pcm,samples,rate}, kClips/kClipCount).
"""

import pathlib
import struct
import sys
import wave

HERE = pathlib.Path(__file__).resolve().parent
BASIC = HERE / "dist" / "basic"
OUT = HERE / "../../src/sfx/sfx_basic_data.h"


def main() -> int:
    wavs = sorted(BASIC.glob("*.wav"))
    if not wavs:
        print(f"no WAVs in {BASIC} - run build_assets.py first")
        return 1

    clips = []
    total = 0
    for p in wavs:
        with wave.open(str(p), "rb") as w:
            assert w.getnchannels() == 1 and w.getsampwidth() == 2, p
            rate = w.getframerate()
            frames = w.readframes(w.getnframes())
        samples = struct.unpack(f"<{len(frames) // 2}h", frames)
        clips.append((p.stem, rate, samples))
        total += len(frames)

    out = OUT.resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        f.write(
            "// GENERATED by tools/sounds/embed_basic.py - DO NOT EDIT.\n"
            "// The embedded basic SFX set: raw 16-bit mono PCM in flash rodata\n"
            "// (played via solide::audio::playPcm - no filesystem needed).\n"
            f"// {len(clips)} clips, {total / 1024:.0f} KB of PCM.\n"
            "// Include from exactly ONE translation unit (sound_fx.cpp).\n"
            "#pragma once\n#include <cstddef>\n#include <cstdint>\n\n"
            "namespace sfx_basic {\n\n"
        )
        for slug, rate, samples in clips:
            ident = slug.replace("-", "_")
            f.write(f"static const int16_t k_{ident}[] = {{\n")
            for i in range(0, len(samples), 16):
                f.write("  " + ",".join(str(s) for s in samples[i : i + 16]) + ",\n")
            f.write("};\n\n")
        f.write(
            "struct Clip {\n  const char*    slug;\n  const int16_t* pcm;\n"
            "  size_t         samples;\n  uint32_t       rate;\n};\n\n"
            "static const Clip kClips[] = {\n"
        )
        for slug, rate, samples in clips:
            ident = slug.replace("-", "_")
            f.write(f'  {{"{slug}", k_{ident}, {len(samples)}, {rate}}},\n')
        f.write(
            "};\nstatic const size_t kClipCount = sizeof(kClips) / sizeof(kClips[0]);\n\n}  // namespace sfx_basic\n"
        )

    print(f"wrote {out} ({len(clips)} clips, {total / 1024:.0f} KB PCM)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
