#!/usr/bin/env python3
"""Generate QR known-answer vectors from Project Nayuki's reference Python
qrcodegen (the algorithm lib/core/src/qr.cpp reimplements). Writes
test/test_qr/qr_vectors.h (embedded into the native Unity suite) - the
test_proto/nsn_vectors pattern.

The encode call pins the exact configuration nimbus::qr::encode() uses: BYTE
mode (make_bytes, never numeric/alnum), ECC level M with boosting DISABLED,
versions 1-6, automatic penalty-based mask selection. Same algorithm + same
inputs => the module maps must agree bit-for-bit.

Run from the Nimbus repo root whenever the vector list changes:
    python3 -m pip install qrcodegen     # reference implementation (MIT)
    python3 tools/gen_qr_vectors.py
"""

from __future__ import annotations

import sys
from pathlib import Path

NIMBUS = Path(__file__).resolve().parent.parent

try:
    from qrcodegen import QrCode, QrSegment
except ImportError:
    sys.exit("gen_qr_vectors.py: missing reference encoder - run `python3 -m pip install qrcodegen` first")

# The two URL shapes the device actually shows (AP fallback + mDNS name), plus
# capacity-edge payloads pinning the version-selection boundaries.
VECTOR_TEXTS = [
    "http://192.168.4.1/",
    "http://nimbus.local/",
    "http://192.0.2.26/",  # a representative STA-IP config URL (configUrl(): http://<ip>/)
    "a" * 14,  # last payload that fits v1-M
    "a" * 15,  # first payload that needs v2-M
    "a" * 106,  # v6-M exactly full
]


def encode(text: str) -> QrCode:
    seg = QrSegment.make_bytes(text.encode("ascii"))
    return QrCode.encode_segments([seg], QrCode.Ecc.MEDIUM, minversion=1, maxversion=6, boostecl=False)


def pack_modules(qr: QrCode) -> bytes:
    """Row-major, MSB-first, bit = dark - nimbus::qr::QrCode packing."""
    size = qr.get_size()
    out = bytearray((size * size + 7) // 8)
    for y in range(size):
        for x in range(size):
            if qr.get_module(x, y):
                i = y * size + x
                out[i >> 3] |= 0x80 >> (i & 7)
    return bytes(out)


def main() -> None:
    lines = [
        "#pragma once",
        "// GENERATED by tools/gen_qr_vectors.py from Project Nayuki's reference",
        "// Python qrcodegen (pip install qrcodegen) - do not edit by hand.",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "struct QrVector {",
        "  const char* text;",
        "  int version;",
        "  int size;",
        "  // Row-major, MSB-first, bit = dark (nimbus::qr::QrCode packing).",
        "  const uint8_t* modules;",
        "};",
        "",
    ]
    names = []
    for n, text in enumerate(VECTOR_TEXTS):
        qr = encode(text)
        packed = pack_modules(qr)
        name = f"k_qr_vec{n}"
        names.append((name, text, qr.get_version(), qr.get_size()))
        arr = ", ".join(f"0x{b:02X}" for b in packed)
        lines.append(f"static const uint8_t {name}_modules[] = {{{arr}}};")
    lines.append("")
    lines.append("static const QrVector kQrVectors[] = {")
    for name, text, version, size in names:
        lines.append(f'  {{"{text}", {version}, {size}, {name}_modules}},')
    lines.append("};")
    lines.append("static const size_t kQrVectorCount = sizeof(kQrVectors) / sizeof(kQrVectors[0]);")
    lines.append("")
    outdir = NIMBUS / "test" / "test_qr"
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "qr_vectors.h").write_text("\n".join(lines))
    print(f"wrote {len(names)} vectors -> {outdir / 'qr_vectors.h'}")
    for name, text, version, size in names:
        label = text if len(text) <= 24 else f"{text[:10]}..({len(text)} chars)"
        print(f"  {label!r}: v{version}, {size}x{size}")


if __name__ == "__main__":
    main()
