#!/usr/bin/env python3
"""Generate nsn protocol test vectors from the reference implementation in
nsnotify (public repo, https://github.com/ristllin/nsnotify). Writes
tools/nsn_vectors.json (cross-repo artifact) and test/test_proto/nsn_vectors.h
(embedded into the native Unity suite).

Run from the Nimbus repo root whenever the reference encoder changes:
    python3 tools/gen_nsn_vectors.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

NIMBUS = Path(__file__).resolve().parent.parent
NOTIFY_HOST = Path(os.environ.get("NIMBUS_NOTIFY_HOST", str(NIMBUS.parent / "nsnotify")))
sys.path.insert(0, str(NOTIFY_HOST))

from notify.broker.frame import FrameSegment, encode_frame  # noqa: E402
from notify.state import Anim, State  # noqa: E402

VECTORS = [
    {
        "name": "empty_ring",
        "segments": [],
        "brightness": 128,
        "seq": 0,
    },
    {
        "name": "single_running",
        "segments": [(State.Running, 170, Anim.Comet, 0)],
        "brightness": 60,
        "seq": 1,
    },
    {
        "name": "default_styles_all_states",
        "segments": [(s, *__import__("notify.state", fromlist=["STATE_STYLE"]).STATE_STYLE[s], 0) for s in State],
        "brightness": 255,
        "seq": 42,
    },
    {
        "name": "mixed_spans_and_white",
        "segments": [
            (State.WaitingInput, 213, Anim.Breathe, 5),
            (State.Idle, 255, Anim.Breathe, 12),  # 255 = white
            (State.Done, 85, Anim.Fade, 0),
        ],
        "brightness": 200,
        "seq": 254,
    },
    {
        "name": "seq_wrap",
        "segments": [(State.Error, 0, Anim.Solid, 45)],
        "brightness": 1,
        "seq": 255,
    },
    {
        "name": "max_segments_16",
        "segments": [(State.Running, (i * 16) % 255, Anim.Comet, 2) for i in range(16)],
        "brightness": 90,
        "seq": 7,
    },
    {
        "name": "overflow_truncated_to_16",  # encoder truncates >16 segs
        "segments": [(State.Idle, 10 + i, Anim.Solid, 1) for i in range(20)],
        "brightness": 33,
        "seq": 9,
    },
]


def main() -> None:
    out = []
    for v in VECTORS:
        segs = [FrameSegment(state=s, hue=h, anim=a, span=sp) for (s, h, a, sp) in v["segments"]]
        packet = encode_frame(segs, v["brightness"], v["seq"])
        kept = segs[:16]
        out.append(
            {
                "name": v["name"],
                "packet_hex": packet.hex(),
                "seq": v["seq"] & 0xFF,
                "brightness": v["brightness"] & 0xFF,
                "segments": [{"state": int(s.state), "hue": s.hue, "anim": int(s.anim), "span": s.span} for s in kept],
            }
        )

    (NIMBUS / "tools" / "nsn_vectors.json").write_text(json.dumps(out, indent=2) + "\n")

    lines = [
        "#pragma once",
        "// GENERATED by tools/gen_nsn_vectors.py from the reference encoder in",
        "// nsnotify/notify/broker/frame.py - do not edit by hand.",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "struct NsnVectorSeg { uint8_t state, hue, anim, span; };",
        "struct NsnVector {",
        "  const char* name;",
        "  const uint8_t* packet;",
        "  size_t packetLen;",
        "  uint8_t seq, brightness, segCount;",
        "  const NsnVectorSeg* segs;",
        "};",
        "",
    ]
    for v in out:
        raw = bytes.fromhex(v["packet_hex"])
        arr = ", ".join(f"0x{b:02X}" for b in raw)
        lines.append(f"static const uint8_t k_{v['name']}_pkt[] = {{{arr}}};")
        if v["segments"]:
            segs = ", ".join(f"{{{s['state']}, {s['hue']}, {s['anim']}, {s['span']}}}" for s in v["segments"])
            lines.append(f"static const NsnVectorSeg k_{v['name']}_segs[] = {{{segs}}};")
        else:
            lines.append(f"static const NsnVectorSeg* k_{v['name']}_segs = nullptr;")
        lines.append("")
    lines.append("static const NsnVector kNsnVectors[] = {")
    for v in out:
        lines.append(
            f"  {{\"{v['name']}\", k_{v['name']}_pkt, sizeof(k_{v['name']}_pkt), "
            f"{v['seq']}, {v['brightness']}, {len(v['segments'])}, k_{v['name']}_segs}},"
        )
    lines.append("};")
    lines.append("static const size_t kNsnVectorCount = sizeof(kNsnVectors) / sizeof(kNsnVectors[0]);")
    lines.append("")
    (NIMBUS / "test" / "test_proto" / "nsn_vectors.h").write_text("\n".join(lines))
    print(f"wrote {len(out)} vectors")


if __name__ == "__main__":
    main()
