// @ts-check
// Curated sidebar for the Nimbus docs. Hand-authored (not autogenerated).
// The information architecture: Intro → Quick Start (do this first) →
// Hardware Build → Using Nimbus (owner topics) → How It Works (internals) →
// Reference → Forking & Contributing.
// Every page the migrate script generates (scripts/migrate-docs.mjs PAGES)
// must appear here - an entry missing from this file is an orphan the site
// never links to.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Quick Start',
      collapsed: false,
      items: [
        'quick-start/what-you-need',
        'quick-start/computer-setup',
        'quick-start/flash',
        'quick-start/setup-wizard',
        'quick-start/first-conversation',
        'quick-start/notifier-quick-start',
        'getting-started/first-time-setup',
      ],
    },
    {
      type: 'category',
      label: 'Hardware Build',
      collapsed: true,
      items: [
        'guides/hardware',
        'guides/hardware-bom',
        'guides/hardware-build-tft',
        'guides/hardware-touch-tft',
        'guides/hardware-all-in-one-cyd',
      ],
    },
    {
      type: 'category',
      label: 'Using Nimbus',
      collapsed: true,
      items: [
        'getting-started/webui-reference',
        'guides/modes-and-signals',
        'guides/led-ux',
        'guides/sfx-map',
        'guides/connectors',
        'guides/mcp',
        'guides/people-and-privacy',
        'guides/notifier-status-language',
      ],
    },
    {
      type: 'category',
      label: 'Cloud',
      collapsed: true,
      items: [
        'cloud/cloud-access',
        'cloud/cumulo-key',
      ],
    },
    {
      type: 'category',
      label: 'How It Works',
      collapsed: true,
      items: [
        'guides/architecture',
        'guides/turn-anatomy',
        'guides/orchestrator-live-turn',
        'guides/orchestrator-world',
        'guides/memory',
        'guides/orchestrator-storage',
        'guides/sub-sessions',
        'guides/harness',
        'guides/provider-wire',
        'guides/security',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/config-and-nvs',
        'reference/tool-catalog',
        'reference/turn-contract',
        'reference/capabilities-matrix',
        'reference/tools-and-commands',
        'reference/changelog',
      ],
    },
    {
      type: 'category',
      label: 'Forking & Contributing',
      collapsed: true,
      items: [
        'contributing/development',
        'contributing/self-hosted-ota',
        'guides/ota',
        'guides/ota-operations',
      ],
    },
  ],
};

module.exports = sidebars;
