#!/usr/bin/env python3
"""gen_webui - assemble the device web UI fragments into a nimbusd header.

Virtual Nimbus (nimbusd) serves the SAME web app the device serves. The device
compiles the page from the PROGMEM fragments in include/web/ui_*.h (ordered by
include/web_pages.h); nimbusd is a POSIX process with no Arduino, so it cannot
include those PROGMEM headers directly. This generator extracts each fragment's
raw-string payload (the exact bytes tools/webui_concat_check.py blesses) and
emits nimbusd/src/webui_page.h - an array of parts nimbusd streams in order.

The output is a GENERATED FILE. Edit the fragments (or this generator), never
webui_page.h by hand. The nimbusd test suite asserts the concatenated parts equal
tools/webui_page.snapshot byte-for-byte, so drift from the device's blessed page
fails the build (the same discipline webui_concat_check.py enforces device-side).

Run from the repo root:  python3 nimbusd/tools/gen_webui.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "include" / "web_pages.h"
SNAPSHOT = ROOT / "tools" / "webui_page.snapshot"
LOGO = ROOT / "include" / "web" / "ui_logo.h"
OUT = ROOT / "nimbusd" / "src" / "webui_page.h"

RAWSTR = re.compile(r'R"=====\((.*)\)====="', re.S)
DELIM = "NIMBUSWEBUI"  # raw-string delimiter for the emitted parts


def fragment_order() -> list[str]:
    manifest = MANIFEST.read_text()
    order = re.findall(r'#include "web/(ui_\w+)\.h"', manifest)
    if not order:
        sys.exit("FAIL: no fragment includes in web_pages.h")
    return order


def payload(path: Path) -> str:
    m = RAWSTR.search(path.read_text())
    if not m:
        sys.exit(f"FAIL: no raw-string payload in {path}")
    return m.group(1)


def logo_literal() -> str:
    """The /logo.svg string literal, extracted verbatim from ui_logo.h so its
    C-string escaping (\" etc.) is preserved exactly."""
    m = re.search(r'UI_LOGO_SVG\[\]\s*PROGMEM\s*=\s*(".*")\s*;', LOGO.read_text(), re.S)
    if not m:
        sys.exit("FAIL: could not extract UI_LOGO_SVG from ui_logo.h")
    lit = m.group(1)
    # Sanity-guard the greedy extraction: the literal must be exactly the SVG
    # string (starts and ends where an <svg>...</svg> C string does), so a stray
    # match can never ship malformed bytes into kLogoSvg.
    if not lit.startswith('"<svg') or not lit.rstrip().endswith('svg>"'):
        sys.exit("FAIL: extracted UI_LOGO_SVG is not a single <svg> string literal")
    return lit


def main() -> None:
    order = fragment_order()
    parts = [payload(ROOT / "include" / "web" / f"{n}.h") for n in order]
    page = "".join(parts)
    logo = logo_literal()

    close = ")" + DELIM + '"'
    for n, p in zip(order, parts):
        if close in p:
            sys.exit(f"FAIL: fragment {n} contains the raw-string close delimiter")

    if SNAPSHOT.exists() and SNAPSHOT.read_text() != page:
        sys.exit("FAIL: assembled page differs from tools/webui_page.snapshot "
                 "(re-bless it device-side with tools/webui_concat_check.py --bless "
                 "if the change is intentional)")

    lines = [
        "#pragma once",
        "// GENERATED by nimbusd/tools/gen_webui.py - DO NOT EDIT BY HAND.",
        "// The Virtual Nimbus web UI: the device's assembled config page (the exact",
        "// bytes tools/webui_page.snapshot blesses), split per include/web/ui_*.h",
        "// fragment so nimbusd streams it identically to the device. Regenerate after",
        "// any fragment change:  python3 nimbusd/tools/gen_webui.py",
        "#include <cstddef>",
        "",
        "namespace nimbusd {",
        "",
        f"// Fragment order (include/web_pages.h): {', '.join(order)}",
        "inline const char* const kWebUiParts[] = {",
    ]
    for p in parts:
        lines.append(f'  R"{DELIM}({p}){DELIM}",')
    lines.append("};")
    lines.append("inline constexpr size_t kWebUiPartCount = "
                 "sizeof(kWebUiParts) / sizeof(kWebUiParts[0]);")
    lines.append("")
    lines.append("// The brand mark served at GET /logo.svg (favicon + sidebar orb), verbatim")
    lines.append("// from include/web/ui_logo.h.")
    lines.append(f"inline const char kLogoSvg[] = {logo};")
    lines.append("")
    lines.append("}  // namespace nimbusd")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"OK: wrote {OUT.relative_to(ROOT)} "
          f"({len(order)} parts, {len(page.encode('utf-8'))} bytes)")


if __name__ == "__main__":
    main()
